import type { NextPage } from 'next'
import Link from 'next/link'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import { wrapper } from 'app/store'
import { selectProfile } from 'app/store/slices/profile'
import { useSelector } from 'react-redux'

const Home: NextPage = (props: any) => {
  const profile = useSelector(selectProfile)
  const { resolvedUrl } = props

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <h1>
            Navigated Page Path: {resolvedUrl}
        </h1>

        <p>
          Profile Name: {profile.name}
        </p>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.tsx</code>
        </p>
        
        <p>
          Navigate to <Link href='/'>Home</Link>
        </p>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export const getServerSideProps = wrapper.getServerSideProps(store => async ({ resolvedUrl }) => {

  return {
    props: {
      resolvedUrl
    }
  }
})

export default Home
